name: Jekyll Theme
url: https://jekylltheme.net
description: Insert tagline here

permalink: /themes/:title

plugins: [jekyll-paginate]

highlighter: pygments
paginate: 20

markdown: rdiscount
rdiscount:
    extensions: ['smart']

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile', 'vendor']
